#!/bin/bash
# Build the drumee-roles source package: the drumee-release anchor plus the seven
# role metapackages, with every component version resolved from
# release-manifest.yaml at build time.
#
#   roles/build.sh              # binary packages (.deb)
#   roles/build.sh --source     # also the source package (.dsc + .tar) for §4
#
# Why this exists rather than a bare dpkg-buildpackage: a Debian source package
# must build standalone, and §4 publishes source/ for AGPL compliance — so the
# manifest cannot be read from the parent directory of an unpacked .dsc. This
# copies the one authoritative manifest into the source tree first. The copy is
# generated and gitignored: editing it instead of the root file would fork the
# single source of truth that §3 exists to protect.
#
# Artifacts land in the repository root, which is where dpkg-buildpackage puts
# them (../ from the source directory) and where the brief's acceptance commands
# look for them.
set -e
if [ "$UID" = "0" ]; then
  echo "You should not run this builder with root privilege"
  exit 1
fi

base="$(dirname "$(readlink -f "$0")")"
root="$(cd "$base/.." && pwd)"
manifest="$root/release-manifest.yaml"
[ -f "$manifest" ] || { echo "missing $manifest" >&2; exit 1; }

BUILD_SOURCE=0
for arg in "$@"; do
  case $arg in
    --source) BUILD_SOURCE=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

# The copy carries a header the root file does not, so a reader who opens the
# wrong one is told immediately.
say "Copying the manifest into the source tree"
{
  printf '# GENERATED by roles/build.sh from ../release-manifest.yaml — DO NOT EDIT.\n'
  printf '# Edit the root release-manifest.yaml; this copy exists only so the source\n'
  printf '# package builds standalone from its .dsc.\n'
  cat "$manifest"
} > "$base/release-manifest.yaml"

cd "$base"
if [ "$BUILD_SOURCE" = 1 ]; then
  say "Building source + binary packages"
  dpkg-buildpackage -us -uc
else
  say "Building binary packages"
  dpkg-buildpackage -us -uc -b
fi

say "Done:"
ls -1 "$root"/drumee-role-*.deb "$root"/drumee-release_*.deb 2>/dev/null | sed 's|^|  |'
